# Generated by Django 4.0.4 on 2022-06-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
